/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Rewards extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Rewards;
  clone(): Rewards;
  methods: {
    accountNonce(accountAddress: string): NonPayableTransactionObject<string>;

    addContract(contractAddress: string): NonPayableTransactionObject<void>;

    claim(
      contractAddress: string,
      amount: number | string | BN,
      signature: string | number[]
    ): NonPayableTransactionObject<void>;

    contracts(arg0: string): NonPayableTransactionObject<{
      active: boolean;
      instance: string;
      0: boolean;
      1: string;
    }>;

    emergencyWithdraw(
      contractAddress: string
    ): NonPayableTransactionObject<void>;

    lastWithdrawAmount(arg0: string): NonPayableTransactionObject<string>;

    lastWithdrawTimestamp(arg0: string): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    recoverAddress(
      contractAddress: string,
      account: string,
      amount: number | string | BN,
      nonce: number | string | BN,
      signature: string | number[]
    ): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setSignerAddress(signerAddress: string): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    updateContract(
      contractAddress: string,
      active: boolean
    ): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
