/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Staking extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Staking;
  clone(): Staking;
  methods: {
    addContract(contractAddress: string): NonPayableTransactionObject<void>;

    contracts(arg0: string): NonPayableTransactionObject<{
      active: boolean;
      instance: string;
      0: boolean;
      1: string;
    }>;

    getStakedTokenTimestamp(
      contractAddress: string,
      tokenId: number | string | BN
    ): NonPayableTransactionObject<string>;

    onERC721Received(
      operator: string,
      arg1: string,
      arg2: number | string | BN,
      arg3: string | number[]
    ): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    stake(
      contractAddress: string,
      tokenIds: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    stakedTokensOfOwner(
      contractAddress: string,
      owner: string
    ): NonPayableTransactionObject<string[]>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    unstake(
      contractAddress: string,
      tokenIds: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    updateContract(
      contractAddress: string,
      active: boolean
    ): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
